### PR TITLE
Fix: Add polyfill for the Mbstring extension

### LINKED ISSUE #6772: Str::reverse() does not support PHP 7.0
## Details

The `Str` helper method `reverse` uses the function [mb_str_split](https://www.php.net/manual/en/function.mb-str-split.php), which requires `PHP 7 >= 7.4.0, PHP 8`.

```bash
FILE: .../runner/work/givewp/givewp/src/Framework/Support/Facades/Str.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 565 | ERROR | The function mb_str_split() is not present in PHP
     |       | version 7.3 or earlier
----------------------------------------------------------------------
```

```php
class Str
{
    public static function reverse($value)
    {
        return implode(array_reverse(mb_str_split($value)));
    }
}
```

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves #6772

## Description

This PR requires the `symphony/polyfill-mbstring` package, which resolves a PHP version compatibility issue related to `Str::reverse()`.

## Testing Instructions

 
The GiveWP plugin should not pass the PHP Compatibility check for `7.0`.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204442996207314

### CODE REVIEW

File: src/Framework/Support/Facades/Str.php [hunk 1]
```diff
@@ -557,6 +557,8 @@ public static function remove($search, $subject, $caseSensitive = true)
     /**
      * Reverse the given string.
      *
+     * @unreleased Required the symfony/polyfill-mbstring package.
+     *
```
Comment (JasonTheAdams) [inline src/Framework/Support/Facades/Str.php:561]: @kjohnson I'm confused by this is being added when there are no actual changes?

**Review by Benunc — APPROVED** [review]
Works for all automated tests.
