### PR TITLE
Fix PHP Notice on fresh install with 2.7.0

### LINKED ISSUE #4820: PHP Notice displaying due to stripe on frontend in a fresh install
## Issue Description

On a fresh install I'm receiving:

This is due to no Stripe account being set and `give_stripe_form_add_credentials()` still attempting to set the data tags.

### PR DESCRIPTION
**Pull request by DevinWalker**
## Description

Resolves #4820 

If no Stripe Account is connected we were causing a PHP Notice to display because `give_stripe_form_add_data_tag_keys()` is using `give_stripe_get_connected_account_id()` which was attempting to pass an non-existent array key.

## Affects

- Fresh Installs
- Stripe

## What to test

- [ ] Install GiveWP fresh
- [ ] View logs

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: includes/gateways/stripe/includes/give-stripe-helpers.php [hunk 1]
```diff
@@ -52,7 +52,7 @@ function give_stripe_get_secret_key( $form_id = 0 ) {
 function give_stripe_get_connected_account_id( $form_id = 0 ) {
 	$default_account = give_stripe_get_default_account( $form_id );
 
-	return trim( $default_account['account_id'] );
+	return isset( $default_account['account_id'] ) ? trim( $default_account['account_id'] ) :  false;
```
Comment (ravinderk) [inline includes/gateways/stripe/includes/give-stripe-helpers.php:55]: @DevinWalker always returns only one data type.  In the above care, this function must return an empty string.

Comment (ravinderk) [reply includes/gateways/stripe/includes/give-stripe-helpers.php:55]: I will take care of this

Comment (ravinderk) [reply includes/gateways/stripe/includes/give-stripe-helpers.php:55]: fixed: https://github.com/impress-org/givewp/compare/0e92af6d0aac...42aa54620744
