### PR TITLE
Fix: update PayPal Commerce payment request data to create order for donation

### LINKED ISSUE #6083: PayPal Donations should be sent as donations instead of purchases.
## Details
Currently, donations made with PayPal Donations are registered as purchases in PayPal.

The workaround, for now, is to use PayPal Standard.

https://givewp.canny.io/admin/board/bug-reports/p/paypal-donations-should-be-sent-as-donations-instead-of-purchases

### PR DESCRIPTION
**Pull request by ravinderk**
Resolves #6083

## Description

I updated the PayPal payment request to submit the order as a Donation.

## Visuals

Transaction details - PayPal 2021-11-09 at 12 41 44 PM

Note:
- "Order Details" section will be added on the transaction details page. These details also appear on the checkbox modal when paying with smart buttons.
- New entries will be added to "Payment Details" section on the transaction details page.

## Testing Instructions

- Create one time donation with smart buttons
- Create one time donation with an advance card field ( I was not able to test because testing cards were not working for me. I am getting authentication error)

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

File: src/PaymentGateways/PayPalCommerce/Repositories/PayPalOrder.php [hunk 1]
```diff
@@ -18,180 +18,206 @@
...
+
+        $request          = new OrdersCreateRequest();
+        $formId           = (int)$array['formId'];
+        $donationCurrency = give_get_currency($formId);
+        $donationAmount   = give_maybe_sanitize_amount(
+            $array['donationAmount'],
+            ['currency' => give_get_currency($formId)]
+        );
+        $request->payPalPartnerAttributionId(give('PAYPAL_COMMERCE_ATTRIBUTION_ID'));
+        $request->body = [
```
Comment (ravinderk) [inline src/PaymentGateways/PayPalCommerce/Repositories/PayPalOrder.php:105]: @JasonTheAdams  code automatically formated in PHPStorm. i made changes on in PayPal payment request body

**Review by JasonTheAdams — APPROVED** [review]
Perfect, @ravinderk! Thanks for busting this out. Please wait for Rick to test before merging.

**Review by rickalday — APPROVED** [review]
